#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Krzysztof Sokołowski
# Assemble the PortMaster package: the directory PortMaster-New's
# ports/olduvai/ holds, and what its build_release.py zips.  Builds no binary
# (build_knulli_release.sh does: the same aarch64 / armhf builds) and ships
# NO GAME CONTENT: game/, mt32-roms/ and soundfonts/ are empty, the player
# copies their own files in.  Refuses to write inside the repo.
#
#   --binary-aarch64 P   the aarch64 binary                      (required)
#   --binary-armhf P     the armhf binary                        (optional)
#   --porter NAME        port.json's porter            (default: the author)
#   --out O              the package directory
#   --release-zip F      also write the zip PortMaster installs (autoinstall):
#                        Olduvai.sh and olduvai/ only, the store files inside
#                        olduvai/ where its installer reads them
#
# Every per-device fact comes from PortMaster at run time, never from this
# script: control.txt and the firmware module (mod_${CFW_NAME}.txt) set up
# the environment, device_info.txt gives the panel, which picks the default
# profile.  The KNULLI launchers (build_port_knulli.sh) stay beside this one
# for the owner's devices.
set -euo pipefail

BIN_AARCH64="" BIN_ARMHF="" OUT="" RELEASE_ZIP=""
PORTER="Krzysztof Sokołowski"
while [ $# -gt 0 ]; do
    case "$1" in
        --binary-aarch64) BIN_AARCH64="$2"; shift 2 ;;
        --binary-armhf)   BIN_ARMHF="$2"; shift 2 ;;
        --porter)         PORTER="$2"; shift 2 ;;
        --out)            OUT="$2"; shift 2 ;;
        --release-zip)    RELEASE_ZIP="$2"; shift 2 ;;
        -h|--help)
            sed -n '4,22p' "$0" | sed 's/^# \{0,1\}//'
            exit 0 ;;
        *) echo "build_port_portmaster: unknown option '$1'" >&2; exit 2 ;;
    esac
done
if [ -z "$BIN_AARCH64" ] || [ -z "$OUT" ]; then
    echo "build_port_portmaster: --binary-aarch64 and --out are required" >&2
    exit 2
fi

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd -P)
# shellcheck source=packaging/port_common.sh
. "${REPO_ROOT}/packaging/port_common.sh"
OUT_ABS=$(port_out_dir build_port_portmaster "$OUT") || exit 1
PORT="${OUT_ABS}/olduvai"
mkdir -p "$PORT"

# ── one binary per architecture (FluidSynth and libmt32emu compiled in) ─────
ARCHES=()
add_arch() {   # <arch> <binary>
    [ -n "$2" ] || return 0
    cp -L "$2" "${PORT}/olduvai.$1"
    chmod +x "${PORT}/olduvai.$1"
    ARCHES+=("$1")
}
add_arch aarch64 "$BIN_AARCH64"
add_arch armhf "$BIN_ARMHF"

port_copy_fonts "$PORT"
port_copy_licenses "$PORT"
# PortMaster keeps every licence under licenses/, ours included.
cp "${PORT}/LICENSE.txt" "${PORT}/licenses/LICENSE"
port_put_files_notes "$PORT" README.txt game mt32-roms soundfonts

# ── gptokeyb: every button unassigned ───────────────────────────────────────
# Olduvai reads the pad through SDL itself (menus, remapping, the Select-held
# shortcuts); gptokeyb runs only for PortMaster's Start+Select kill switch.
{
    echo "# Gameplay input is Olduvai's own (SDL game controller); gptokeyb"
    echo "# runs for PortMaster's Start+Select kill switch only."
    for k in back start guide a b x y l1 l2 l3 r1 r2 r3 up down left right \
             left_analog_up left_analog_down left_analog_left left_analog_right \
             right_analog_up right_analog_down right_analog_left \
             right_analog_right a_hk b_hk x_hk y_hk l1_hk l2_hk r1_hk r2_hk; do
        printf '%s = \\"\n' "$k"
    done
} > "${PORT}/olduvai.gptk"

# ── the launcher ────────────────────────────────────────────────────────────
cat > "${OUT_ABS}/Olduvai.sh" <<'LAUNCH'
#!/bin/bash
# Olduvai — PortMaster launcher.  Generated by packaging/build_port_portmaster.sh.

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
  controlfolder="$XDG_DATA_HOME/PortMaster"
else
  controlfolder="/roms/ports/PortMaster"
fi

source $controlfolder/control.txt
source $controlfolder/device_info.txt

# One binary per architecture, each native: never the 32-bit userland.
export PORT_32BIT="N"
[ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"

get_controls

GAMEDIR="/$directory/ports/olduvai"
cd "$GAMEDIR" || exit 1

> "$GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1

$ESUDO chmod 666 /dev/tty1
$ESUDO chmod 666 /dev/uinput

# Player state lives in the port: settings and saves (XDG_CONFIG_HOME), F5
# bug reports and the log.  An update replaces the build and never these.
export XDG_CONFIG_HOME="$GAMEDIR/conf"
export OLDUVAI_BUG_DIR="$GAMEDIR/bug_reports"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"

# The starting style, from the panel PortMaster reports: the largest scale whose
# frame fits its height, a step every 200 lines.  800 lines and up start
# Enhanced at x4 (a 1280x800 panel is exactly 4x), 600 and up at x3 (the
# Powkiddy A12's 1024x600), 400 and up at x2, a 4:3 panel filling its screen;
# anything shorter Classic.  A DEFAULT below the player's play.json, so a choice
# made under Options -> Style sticks.
W=${DISPLAY_WIDTH:-0}
H=${DISPLAY_HEIGHT:-0}
if [ "$H" -ge 800 ]; then
  PROFILE="hd-handheld-x4"
elif [ "$H" -ge 600 ]; then
  PROFILE="hd-handheld"
elif [ "$H" -ge 400 ] && [ $((W * 3)) -eq $((H * 4)) ]; then
  PROFILE="hd-handheld-43"
elif [ "$H" -ge 400 ]; then
  PROFILE="hd-handheld-x2"
else
  PROFILE="dos-handheld"
fi

# Optional local overrides (debug env vars): never shipped.
[ -f ./olduvai.env ] && . ./olduvai.env

set -- --game-dir ./game --rom-dir ./mt32-roms --default-profile "$PROFILE"
# The engine does not search beside itself for a SoundFont: hand one over.
for sf in ./soundfonts/*.sf2 ./soundfonts/*.sf3; do
  if [ -f "$sf" ]; then set -- "$@" --soundfont "$sf"; break; fi
done

# An install can carry a gptokeyb of the wrong architecture (an aarch64 one on
# an armhf A12): take the helper built for this device when PortMaster has it.
[ -x "$controlfolder/gptokeyb.${DEVICE_ARCH}" ] && \
  GPTOKEYB="$ESUDO $controlfolder/gptokeyb.${DEVICE_ARCH} $ESUDOKILL"
$GPTOKEYB "olduvai.${DEVICE_ARCH}" -c "$GAMEDIR/olduvai.gptk" &
pm_platform_helper "$GAMEDIR/olduvai.${DEVICE_ARCH}" >/dev/null
./olduvai.${DEVICE_ARCH} "$@"

pm_finish
LAUNCH
chmod +x "${OUT_ABS}/Olduvai.sh"

# ── the player's README, inside the port (PUT-FILES-HERE points here) ──────
cat > "${PORT}/README.txt" <<README
Olduvai (PortMaster)
====================

Olduvai is a native recreation of the ENGINE of Prehistorik (1991).  It ships no
game content and reads your own game files.  Get the game from GOG.com
("Prehistorik 1+2") or use your original DOS copy.


game  --  WHERE THE GAME FILES GO (the only step you must do)
-------------------------------------------------------------
$(port_readme_game_files ports/olduvai/game/)


mt32-roms / soundfonts  --  MUSIC
---------------------------------
$(port_readme_music ports/olduvai)


IF IT DOES NOT START
--------------------
Read  ports/olduvai/log.txt .  Its first line names the build; quote it in a
bug report.  A missing game file names the folder searched and the files wanted.


LICENCE
-------
Olduvai is free software, GPL-3.0-or-later (LICENSE.txt).  Third-party
components and their licences are in licenses/ and fonts/.  Source code:
https://github.com/ksokolowski/olduvai
README

# ── the store listing: screenshot, metadata, README.md ──────────────────────
# One curated still (assets/screenshots/README.md allows a port's store
# listing), 4:3 with the bars a 4:3 handheld shows.
cp "${REPO_ROOT}/assets/screenshots/classic-l1-4x3.png" "${OUT_ABS}/screenshot.png"
cp "${OUT_ABS}/screenshot.png" "${PORT}/screenshot.png"

DESC="The 1991 caveman platformer on Olduvai, a native recreation of its engine. Classic DOS plays it exactly as it was; Enhanced HD adds smooth motion, widescreen margins and sharp upscaled graphics. Switch any time under Options - Style."
INST="Needs your own copy of the game (GOG's Prehistorik 1+2, or the DOS original): copy FILESA.CUR, FILESB.CUR, FILESA.VGA, FILESB.VGA and HISTORIK.EXE (or GOG's PREH.SQZ) into ports/olduvai/game/. Roland MT-32 / CM-32L ROMs (ports/olduvai/mt32-roms/) or a SoundFont (ports/olduvai/soundfonts/) are optional; without them the AdLib / Sound Blaster sound plays."
ARCH_JSON=$(printf '"%s", ' "${ARCHES[@]}"); ARCH_JSON="[${ARCH_JSON%, }]"
python3 - "$OUT_ABS/port.json" "$PORTER" "$DESC" "$INST" "$ARCH_JSON" <<'PY'
import json, sys
path, porter, desc, inst, arch = sys.argv[1:]
port = {
    "version": 4,
    "name": "olduvai.zip",
    "items": ["Olduvai.sh", "olduvai"],
    "items_opt": [],
    "attr": {
        "title": "Olduvai",
        "porter": [porter],
        "desc": desc,
        "desc_md": None,
        "inst": inst,
        "inst_md": None,
        "genres": ["platformer"],
        "image": None,
        "rtr": False,
        "exp": False,
        "runtime": [],
        "min_glibc": "2.17",
        "reqs": [],
        "arch": json.loads(arch),
    },
}
with open(path, "w", encoding="utf-8") as f:
    json.dump(port, f, indent=4, ensure_ascii=False)
    f.write("\n")
PY

# <name> is the engine's, never the game's (owner, 2026-09-14); <developer>
# is ours: naming the original's would say they made this port.
cat > "${OUT_ABS}/gameinfo.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<gameList>
  <game>
    <path>./Olduvai.sh</path>
    <name>Olduvai</name>
    <desc>${DESC}</desc>
    <releasedate>19910101T000000</releasedate>
    <developer>${PORTER}</developer>
    <genre>Platform</genre>
    <image>./olduvai/screenshot.png</image>
  </game>
</gameList>
XML

cat > "${OUT_ABS}/README.md" <<'MD'
## Notes

Olduvai is a native recreation of the engine of **Prehistorik** (1991). It
ships no game content: copy your own game files into `ports/olduvai/game/`
(`FILESA.CUR`, `FILESB.CUR`, `FILESA.VGA`, `FILESB.VGA`, and `HISTORIK.EXE` or
GOG's `PREH.SQZ`). The game is sold by [GOG.com](https://www.gog.com/game/prehistorik_12).

Classic DOS plays it as it was in 1991; Enhanced HD adds smooth motion,
widescreen margins and upscaled graphics (Options - Style). Panels 600 lines
tall and up start in Enhanced (scaled x3, x4 from 800 lines, x2 from 400, a
4:3 panel filling its screen), shorter ones in Classic.

If Olduvai does not appear in Ports after installing, update the game list
(Start - Game Settings - Update Gamelists) or restart EmulationStation: on some
firmwares PortMaster's own refresh does not take effect.

Thanks to Titus Interactive, who created Prehistorik in 1991. Olduvai is not
affiliated with or endorsed by them or by any rights holder.

## Controls

| Button | Action |
|--|--|
| D-pad / left stick | Move (up also jumps) |
| A (right) | Jump, confirm in menus |
| B (bottom) | Attack, back in menus |
| Start | Pause menu |
| Select + R1 / L1 | Quicksave / quickload |
| Select + top / left | Cheats (when on) / bug report |
| Start + Select | Quit (PortMaster) |

Buttons can be remapped under Options - Controls.

## Building

Source and build instructions: https://github.com/ksokolowski/olduvai
(`packaging/build_knulli_release.sh` builds the aarch64 and armhf binaries,
`packaging/build_port_portmaster.sh` this package).
MD

echo "PortMaster package ($(IFS=' '; echo "${ARCHES[*]}")) written to ${OUT_ABS}"
(cd "${OUT_ABS}" && find . -type f | sed 's|^\./||' | sort) |
    while IFS= read -r f; do
        printf '  %10s  %s\n' "$(wc -c < "${OUT_ABS}/${f}" | tr -d ' ')" "${f}"
    done

# ── the zip PortMaster installs ─────────────────────────────────────────────
# The directory above is PortMaster-New's repository layout (store files beside
# the launcher).  Its INSTALLER (harbourmaster) wants them inside the port
# folder: it merges olduvai/gameinfo.xml into EmulationStation's game list
# (name, description, the screenshot as the launcher image) and keeps
# olduvai/port.json.  Loose at the zip's root they are tolerated, never merged
# and left as clutter in ports/.  So the zip holds Olduvai.sh and olduvai/ only.
if [ -n "${RELEASE_ZIP}" ]; then
    mkdir -p "$(dirname "${RELEASE_ZIP}")"
    ZIP_ABS="$(cd "$(dirname "${RELEASE_ZIP}")" && pwd -P)/$(basename "${RELEASE_ZIP}")"
    case "${ZIP_ABS}" in
        "${REPO_ROOT}/"*)
            echo "build_port_portmaster: refusing to write a zip inside the repo." >&2
            exit 1 ;;
    esac
    python3 - "${OUT_ABS}" "${ZIP_ABS}" <<'PY'
import os, sys, zipfile
src, dst = sys.argv[1], sys.argv[2]
INSIDE = ("port.json", "gameinfo.xml", "README.md")   # root -> olduvai/
if os.path.exists(dst):
    os.remove(dst)
with zipfile.ZipFile(dst, "w", zipfile.ZIP_DEFLATED) as z:
    def put(path, arc):
        info = zipfile.ZipInfo(arc, date_time=(2026, 1, 1, 0, 0, 0))
        mode = 0o755 if os.access(path, os.X_OK) or arc.endswith(".sh") else 0o644
        info.external_attr = (0o100000 | mode) << 16
        info.compress_type = zipfile.ZIP_DEFLATED
        with open(path, "rb") as f:
            z.writestr(info, f.read())
    put(os.path.join(src, "Olduvai.sh"), "Olduvai.sh")
    for root, _dirs, files in sorted(os.walk(os.path.join(src, "olduvai"))):
        for name in sorted(files):
            path = os.path.join(root, name)
            put(path, os.path.relpath(path, src).replace(os.sep, "/"))
    for name in INSIDE:
        put(os.path.join(src, name), "olduvai/" + name)
PY
    echo "PortMaster release zip written to ${ZIP_ABS} ($(wc -c < "${ZIP_ABS}" | tr -d ' ') bytes)"
fi
