# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Krzysztof Sokołowski
# Writes ${OUT}, the one-function source behind olduvai::build_id()
# (src/core/build_id.hpp).  Runs at BUILD time, on every build, from the
# olduvai_build_id target — a value captured at configure time goes stale
# the moment you commit without reconfiguring, which is the stale-binary
# trap this ID exists to expose.  The file is rewritten only when its text
# changes, so an unchanged ID costs no recompile and no relink.
#
#   clean tree:  "a97f2a7, 2026-09-13 10:41"            hash + COMMIT time
#   dirty tree:  "a97f2a7-dirty, built 2026-09-13 11:02" hash + BUILD time
#   no git:      "unknown"
#
# Commit time for a clean tree so the same source always yields the same
# string (it is the commit's own timezone, not the builder's).  A dirty build
# is exactly where a bare hash would lie, so it is flagged and stamped with
# when it was built (string(TIMESTAMP) honours SOURCE_DATE_EPOCH).
#
# Inputs: -DSRC_DIR=<repo> -DOUT=<generated .cpp> [-DGIT=<git executable>]

set(id "unknown")
if(GIT)
    execute_process(COMMAND "${GIT}" -C "${SRC_DIR}" rev-parse --short=7 HEAD
                    OUTPUT_VARIABLE hash RESULT_VARIABLE rc
                    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(rc EQUAL 0 AND hash)
        execute_process(COMMAND "${GIT}" -C "${SRC_DIR}" status --porcelain
                                --untracked-files=no
                        OUTPUT_VARIABLE dirty OUTPUT_STRIP_TRAILING_WHITESPACE
                        ERROR_QUIET)
        if(dirty)
            string(TIMESTAMP now "%Y-%m-%d %H:%M")
            set(id "${hash}-dirty, built ${now}")
        else()
            execute_process(COMMAND "${GIT}" -C "${SRC_DIR}" log -1
                                    "--format=%cd" "--date=format:%Y-%m-%d %H:%M"
                            OUTPUT_VARIABLE when OUTPUT_STRIP_TRAILING_WHITESPACE
                            ERROR_QUIET)
            set(id "${hash}, ${when}")
        endif()
    endif()
endif()

set(text "// Generated by cmake/build_id.cmake at build time — do not edit.
#include \"core/build_id.hpp\"

namespace olduvai {
const char* build_id() { return \"${id}\"; }
}  // namespace olduvai
")
set(old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL text)
    file(WRITE "${OUT}" "${text}")
endif()
