# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Krzysztof Sokołowski
# Generate a .cpp exposing a text file's content as a raw string literal.
# Used to compile data/menus.json into the binary so a lone executable has
# a working pause menu (an on-disk data/menus.json still overrides it).
#
#   cmake -DIN=<file> -DOUT=<file.cpp> -DSYMBOL=<function name> -P embed_text.cmake
file(READ "${IN}" _content)
if(_content MATCHES "\\)OLDUVAI_EMBED\"")
    message(FATAL_ERROR "embed_text: input contains the raw-string delimiter")
endif()
file(WRITE "${OUT}" "\
// Generated by cmake/embed_text.cmake from ${IN} — do not edit.
namespace olduvai::presentation {
const char* ${SYMBOL}() {
    return R\"OLDUVAI_EMBED(${_content})OLDUVAI_EMBED\";
}
}  // namespace olduvai::presentation
")
