# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Krzysztof Sokołowski
# Turn assets/data/menus.json into C++ that BUILDS the MenuModel directly.
#
# menus.json stays the authoring format — it is a far better place to edit
# menus than C++ initialisers, and it is where future translations would go.
# What changes is when it is read: at build time, here, instead of by a
# hand-rolled JSON parser inside the shipped binary.
#
# This replaces embed_text.cmake for menus: that embedded the JSON as a raw
# string literal, so the binary still parsed JSON at startup — the build had
# already read the file and then handed the work to the runtime anyway.
#
# A malformed menus.json now fails the BUILD, which is where a typo in a menu
# definition should surface, rather than degrading to a menu-less binary.
#
# Uses only string(JSON ...) (CMake >= 3.19; the project requires 3.21), so it
# adds no build dependency — important for the Tier-3 handheld toolchains.
#
#   cmake -DIN=<menus.json> -DOUT=<generated.cpp> -P gen_menu_model.cmake

cmake_minimum_required(VERSION 3.21)

if(NOT DEFINED IN OR NOT DEFINED OUT)
    message(FATAL_ERROR "gen_menu_model: need -DIN=<json> -DOUT=<cpp>")
endif()

file(READ "${IN}" _json)

# C++ string-literal escaping.  Menu labels are plain today; this is here so a
# future translation with a quote or a backslash cannot silently break the
# generated file.
function(_cxx_quote out_var text)
    string(REPLACE "\\" "\\\\" text "${text}")
    string(REPLACE "\"" "\\\"" text "${text}")
    string(REPLACE "\n" "\\n" text "${text}")
    set(${out_var} "\"${text}\"" PARENT_SCOPE)
endfunction()

# Optional string member -> C++ literal ("" when absent), mirroring opt_str().
function(_opt_str out_var obj key)
    string(JSON _v ERROR_VARIABLE _e GET "${obj}" "${key}")
    if(_e)
        set(${out_var} "\"\"" PARENT_SCOPE)
    else()
        _cxx_quote(_q "${_v}")
        set(${out_var} "${_q}" PARENT_SCOPE)
    endif()
endfunction()

set(_out "// GENERATED FROM assets/data/menus.json — DO NOT EDIT.\n")
string(APPEND _out "// Regenerated by cmake/gen_menu_model.cmake on every build.\n")
string(APPEND _out "// SPDX-License-Identifier: GPL-3.0-or-later\n\n")
string(APPEND _out "#include \"presentation/menu/menu_model.hpp\"\n\n")
string(APPEND _out "namespace olduvai::presentation {\n\n")
string(APPEND _out "MenuModel built_in_menu_model() {\n")
string(APPEND _out "    MenuModel m;\n")

string(JSON _screens GET "${_json}" screens)
string(JSON _nscreens LENGTH "${_screens}")
math(EXPR _slast "${_nscreens} - 1")

foreach(_si RANGE 0 ${_slast})
    string(JSON _sid MEMBER "${_screens}" ${_si})
    string(JSON _screen GET "${_screens}" "${_sid}")
    string(JSON _header GET "${_screen}" header)
    _cxx_quote(_qsid "${_sid}")
    _cxx_quote(_qheader "${_header}")
    string(APPEND _out "    {\n        MenuScreen s;\n")
    string(APPEND _out "        s.header = ${_qheader};\n")

    string(JSON _items GET "${_screen}" items)
    string(JSON _nitems LENGTH "${_items}")
    if(_nitems GREATER 0)
        math(EXPR _ilast "${_nitems} - 1")
        foreach(_ii RANGE 0 ${_ilast})
            string(JSON _item GET "${_items}" ${_ii})
            string(JSON _id GET "${_item}" id)
            string(JSON _type GET "${_item}" type)
            string(JSON _label GET "${_item}" label)
            _cxx_quote(_qid "${_id}")
            _cxx_quote(_qtype "${_type}")
            _cxx_quote(_qlabel "${_label}")
            _opt_str(_qhint "${_item}" hint)
            _opt_str(_qtarget "${_item}" target)
            _opt_str(_qaction "${_item}" action)
            _opt_str(_qkey "${_item}" key)

            string(APPEND _out "        {\n            MenuItem it;\n")
            string(APPEND _out "            it.id = ${_qid};\n")
            string(APPEND _out "            it.type = ${_qtype};\n")
            string(APPEND _out "            it.label = ${_qlabel};\n")
            string(APPEND _out "            it.hint = ${_qhint};\n")
            string(APPEND _out "            it.target = ${_qtarget};\n")
            string(APPEND _out "            it.action = ${_qaction};\n")
            string(APPEND _out "            it.key = ${_qkey};\n")

            # values[]: numbers become their integer token, exactly as
            # num_token() did (every numeric value in the file is an integer;
            # a fractional one would need the same to_string(double) form).
            string(JSON _vals ERROR_VARIABLE _ev GET "${_item}" values)
            if(NOT _ev)
                string(JSON _nv LENGTH "${_vals}")
                if(_nv GREATER 0)
                    math(EXPR _vlast "${_nv} - 1")
                    foreach(_vi RANGE 0 ${_vlast})
                        string(JSON _v GET "${_vals}" ${_vi})
                        string(JSON _vt TYPE "${_vals}" ${_vi})
                        if(_vt STREQUAL "NUMBER")
                            math(EXPR _vint "${_v}")
                            set(_qv "\"${_vint}\"")
                        else()
                            _cxx_quote(_qv "${_v}")
                        endif()
                        string(APPEND _out "            it.values.push_back(${_qv});\n")
                    endforeach()
                endif()
            endif()

            string(JSON _vls ERROR_VARIABLE _el GET "${_item}" value_labels)
            if(NOT _el)
                string(JSON _nl LENGTH "${_vls}")
                if(_nl GREATER 0)
                    math(EXPR _llast "${_nl} - 1")
                    foreach(_li RANGE 0 ${_llast})
                        string(JSON _l GET "${_vls}" ${_li})
                        _cxx_quote(_ql "${_l}")
                        string(APPEND _out "            it.value_labels.push_back(${_ql});\n")
                    endforeach()
                endif()
            endif()

            foreach(_num min max step)
                string(JSON _n ERROR_VARIABLE _en GET "${_item}" ${_num})
                if(NOT _en)
                    string(APPEND _out "            it.${_num} = ${_n};\n")
                endif()
            endforeach()

            string(JSON _rst ERROR_VARIABLE _er GET "${_item}" restart)
            if(NOT _er)
                if(_rst)
                    string(APPEND _out "            it.restart = true;\n")
                endif()
            endif()

            string(APPEND _out "            s.items.push_back(std::move(it));\n        }\n")
        endforeach()
    endif()

    string(APPEND _out "        m.screens[${_qsid}] = std::move(s);\n    }\n")
endforeach()

string(APPEND _out "    return m;\n}\n\n")
string(APPEND _out "}  // namespace olduvai::presentation\n")

file(WRITE "${OUT}" "${_out}")
